export const ROUTES = {
  HOME: "/",
  GENDER_REVEAL: "/gender-reveal",
  NATIONALITY_REVEAL: "/nationality-reveal",
  COUNTER: "/counter",
  SPACE_MISSION: "/space-mission",
  IDEAL_WEIGHT: "/ideal-weight",
  CONTACTS: "/contacts",
  ABOUT: "/about",
  PROFILE: "/profile",
  PROFILE_DATA: "/profile/data",
  PROFILE_SETTINGS: "/profile/settings",
  NOT_FOUND: "*",
  PRODUCT: (id: string | number) => `/products/${id}`,
  USERS: "/users",
  USER: (id: string | number) => `/users/${id}`,
} as const;
